name: Nightly Test

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

concurrency:
  group: nightly-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-test-eval-text-models:
    if: github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run eval test for text models
        timeout-minutes: 120
        run: |
          cd test/srt
          python3 test_nightly_gsm8k_eval.py

  nightly-test-perf-text-models:
    if: github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run performance test for text models
        timeout-minutes: 180
        env:
          TRACE_BASE_URL: https://raw.githubusercontent.com/mickqian/SGLang-test-nightly/main/traces/${{ github.run_id }}
        run: |
          rm -rf test/srt/performance_profiles_text_models/
          cd test/srt
          python3 test_nightly_text_models_perf.py

      - name: Checkout storage repo (SGLang-test-nightly)
        uses: actions/checkout@v4
        with:
          repository: mickqian/SGLang-test-nightly
          token: ${{ secrets.NIGHTLY_PUSH_TOKEN }}
          path: nightly-storage

      - name: Publish traces to storage repo
        run: |
          mkdir -p nightly-storage/traces/${{ github.run_id }}
          cp -v test/srt/performance_profiles_text_models/*.json nightly-storage/traces/${{ github.run_id }}/ || true
          cd nightly-storage
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Nightly traces for run ${{ github.run_id }} at ${{ github.run_number }}"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

  nightly-test-eval-vlm-models:
    if: github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run eval test for VLM models (MMMU-100)
        timeout-minutes: 240
        run: |
          cd test/srt
          python3 test_nightly_vlm_mmmu_eval.py

      - name: Print performance table if exists
        run: |
          python3 - <<'PY'
          import os
          p = 'test/srt/performance_report.md'
          if not os.path.exists(p):
              print('Report not found, skip printing')
              raise SystemExit(0)
          s = open(p, 'r').read()
          # append to GitHub summary
          with open(os.environ['GITHUB_STEP_SUMMARY'], 'a') as f:
              f.write('\n')
              f.write(s)
          PY

  nightly-test-perf-vlm-models:
    if: github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run perf test for VLM models (MMMU-100)
        timeout-minutes: 240
        env:
          TRACE_BASE_URL: https://raw.githubusercontent.com/mickqian/SGLang-test-nightly/main/traces/${{ github.run_id }}
        run: |
          rm -rf test/srt/performance_profiles_vlms/
          cd test/srt
          python3 test_nightly_vlm_models_perf.py

      - name: Checkout storage repo (SGLang-test-nightly)
        uses: actions/checkout@v4
        with:
          repository: mickqian/SGLang-test-nightly
          token: ${{ secrets.NIGHTLY_PUSH_TOKEN }}
          path: nightly-storage

      - name: Publish traces to storage repo
        run: |
          mkdir -p nightly-storage/traces/${{ github.run_id }}
          cp -v test/srt/performance_profiles_vlms/*.json nightly-storage/traces/${{ github.run_id }}/ || true
          cd nightly-storage
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Nightly VLM traces for run ${{ github.run_id }} at ${{ github.run_number }}"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

      - name: Print VLM performance table if exists
        run: |
          python3 - <<'PY'
          import os
          p = 'test/srt/vlm_performance_report.md'
          if not os.path.exists(p):
              print('VLM Report not found, skip printing')
              raise SystemExit(0)
          s = open(p, 'r').read()
          # append to GitHub summary
          with open(os.environ['GITHUB_STEP_SUMMARY'], 'a') as f:
              f.write('\n')
              f.write(s)
          PY
