name: Nightly Test

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

concurrency:
  group: nightly-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-test-eval-text-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run eval test for text models
        timeout-minutes: 120
        run: |
          cd test/srt
          python3 test_nightly_text_models_gsm8k_eval.py

  nightly-test-perf-text-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh
          apt-get install rsync -y
          apt install git-lfs

      - name: Run performance test for text models
        timeout-minutes: 180
        env:
          TRACE_BASE_URL: https://huggingface.co/Miiiick/ci-data/resolve/main/traces/${{ github.run_id }}
          PERFETTO_RELAY_URL: ${{ vars.PERFETTO_RELAY_URL }}
        run: |
          rm -rf test/srt/performance_profiles_text_models/
          cd test/srt
          python3 test_nightly_text_models_perf.py

      - name: Checkout storage repo (Hugging Face)
        uses: actions/checkout@v4
        with:
          repository: Miiiick/ci-data
          token: ${{ secrets.NIGHTLY_PUSH_TOKEN }}
          path: nightly-storage

      - name: Publish traces to storage repo
        run: |
          mkdir -p nightly-storage/traces/${{ github.run_id }}
          if [ -d test/srt/performance_profiles_text_models ]; then
            rsync -av --include='/' --include='.json.gz' --exclude='' test/srt/performance_profiles_text_models/ nightly-storage/traces/${{ github.run_id }}/
          fi
          cd nightly-storage
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Nightly traces for run ${{ github.run_id }} at ${{ github.run_number }}"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

  nightly-test-eval-vlm-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run eval test for VLM models (fixed MMMU-100)
        timeout-minutes: 240
        run: |
          cd test/srt
          python3 test_nightly_vlm_mmmu_eval.py


  nightly-test-perf-vlm-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh
          apt-get install rsync -y
          apt install git-lfs

      - name: Run perf test for VLM models (MMMU)
        timeout-minutes: 240
        env:
          TRACE_BASE_URL: https://huggingface.co/Miiiick/ci-data/resolve/main/traces/${{ github.run_id }}
          PERFETTO_RELAY_URL: ${{ vars.PERFETTO_RELAY_URL }}
        run: |
          rm -rf test/srt/performance_profiles_vlms/
          cd test/srt
          python3 test_nightly_vlm_models_perf.py

#      - name: Checkout storage repo (Hugging Face)
#        uses: actions/checkout@v4
#        with:
#          repository: Miiiick/ci-data
#          token: ${{ secrets.NIGHTLY_PUSH_TOKEN }}
#          path: nightly-storage

      - name: Checkout storage repo (Hugging Face)
        run: |
          git lfs install
          git lfs track "*.gz"
          git clone https://huggingface.co/Miiiick/ci-data nightly-storage
          # git -C nightly-storage config --unset-all http.https://huggingface.co/.extraHeader || true

      - name: Publish traces to storage repo
        env:
          HF_TOKEN: ${{ secrets.NIGHTLY_PUSH_TOKEN }}
        run: |
          mkdir -p nightly-storage/traces/${{ github.run_id }}
          if [ -d test/srt/performance_profiles_vlms ]; then
            rsync -av --include='/' --include='.json.gz' --exclude='' test/srt/performance_profiles_vlms/ nightly-storage/traces/${{ github.run_id }}/
          fi
          cd nightly-storage
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Nightly traces for run ${{ github.run_id }} at ${{ github.run_number }}"
            git push https://github-actions[bot]:$HF_TOKEN@huggingface.co/Miiiick/ci-data main
          else
            echo "No changes to commit"
          fi
